/*
-- Query: SELECT * FROM test.MedicalFileSpecialty
LIMIT 0, 1000

-- Date: 2024-07-03 18:52
*/
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (1,'0108 OPHTHALMOLOGY -1','طب العيون');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (2,'Othar','اخري');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (3,'0160 Dentistry','اسنان');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (4,'0101 Internal Medicine','باطنة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (5,'0104 Obstetrics and Gynecology','طب النساء والتوليد');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (6,'0109 Dermatology','الأمراض الجلدية');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (7,'0103 Pediatrics','طب الأطفال');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (8,'0102 General Surgery','الجراحة العامة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (9,'01110103 Cardiology Specialist Examination','طب القلب');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (10,'01080103 Ophthalmology Specialist Examination','لطب العيون');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (11,'01040101 Obstetrics and Gynecology Junior Examination','طب النساء والتوليد');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (12,'01040103 Obstetrics and Gynecology Specialist Examination','طب النساء والتوليد');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (13,'01050101 Orthopedics Junior Examination','طب عظام');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (14,'01010101 Internal Medicine Junior Examination','طب باطنة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (15,'Internal Medicine Specialist Examination 1','لفحص التخصصي للطب الباطني');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (16,'01020101 General Surgery Junior Examination','الجراحة العامة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (17,'01080104 Ophthalmology Consultant Examination','طب وجراحة العيون');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (18,'Pediatrics Junior Examination 1','طب الأطفال');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (19,'Orthopedics Specialist Examination 1','لجراحة العظام');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (20,'01070101 ENT Junior Examination','الأنف والأذن والحنجرة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (21,'01090101 Dermatology Junior Examination','الأمراض الجلدية');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (22,'01030103 Pediatrics Specialist Examination','لطب الأطفال');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (23,'016011 Dental Examination','طب الاسنان');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (24,'01060101 Urology Junior Examination','المسالك البولية');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (25,'01060103 Urology Specialist Examination','لجراحة المسالك البولية');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (26,'0107 ENT','الأنف والأذن والحنجرة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (27,'01020104 General Surgery Consultant Examination','الجراحة العامة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (28,'01030104 Pediatrics Consultant Examination','طب الأطفال');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (29,'01020103 General Surgery Specialist Examination','للجراحة العامة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (30,'Open file','فتح ملف');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (31,'0105 Orthopedics','طب العظام');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (32,'02 Radiology','الأشعة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (33,'0108 Ophthalmology','طب العيون');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (34,'0113 Psychiatry','الطب النفسي');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (35,'0106 Urology','المسالك البولية');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (36,'0111 Cardiology','أمراض القلب');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (37,'010202 General Surgery OPD Services','الجراحة العامة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (38,'01150103 Neurosurgery Specialist Examination','جراحة المخ والأعصاب');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (39,'0115 Neurosurgery','جراحة الاعصاب');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (40,'0180 Physiotherapy','العلاج الطبيعي');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (41,'01100103 Vascular Surgery Specialist Examination','جراحة الأوعية الدموية');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (42,'0119 Respiratory','طب تنفسي');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (43,'01010102 Internal Medicine Senior Examination','الطب الباطني');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (44,'Internal Medicine Specialist Examination 2 (radiology)','للطب الباطني');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (45,'Urology Specialist Examination 1','جراحة المسالك البولية');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (46,'دخول','دخول');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (47,'01070103 ENT Specialist Examination','الأنف والأذن والحنجرة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (48,'01070104 ENT Consultant Examination','الأنف والأذن والحنجرة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (49,'01010103 Internal Medicine Specialist Examination','للطب الباطني');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (50,'0114 Endocrinology -1','الغدد الصماء');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (51,'0135 Plastic Surgery','جراحة تجميلية');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (52,'01080101 Ophthalmology Junior Examination','طب العيون');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (53,'0122 Emergency Medicine','طب الطوارئ');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (54,'0112 Gastroenterology and Hepatology-1','طب الجهاز الهضمي والكبد');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (55,'0134 Maxillofacial Surgery','جراحة الوجه والفكين');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (56,'0117 Hematology','أمراض الدم');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (57,'0121 Nephrology','أمراض الكلى');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (58,'0185 Medical Equipments and tools','المعدات والأدوات الطبية');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (59,'01090104 Dermatology Consultant Examination','طب الجلدية');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (60,'01150104 Neurosurgery Consultant Examination','جراحة المخ والأعصاب');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (61,'01010104 Internal Medicine Consultant Examination','الطب الباطني');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (62,'01040102 Obstetrics and Gynecology Senior Examination','طب النساء والتوليد');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (63,'01120101 Gastroenterology and Hepatology Junior Examination','أمراض الجهاز الهضمي والكبد');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (64,'01170103 Hematology Specialist Examination','التخصصي لأمراض الدم');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (65,'01030105 Pediatrics Professor Examination','طب الأطفال');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (66,'0110 Vascular Surgery','جراحة الأوعية الدموية');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (67,'01030101 Pediatrics Junior Examination','طب الأطفال');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (68,'04 Others','أخرى');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (69,'19001 Common procesures','الإجراءات المشتركة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (70,'01040104 Obstetrics and Gynecology Consultant Examination','أمراض النساء والتوليد');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (71,'01070105 ENT Professor Examination','الأنف والأذن والحنجرة');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (72,'01190101 01190101 Respiratory Junior Examination','فحص الجهاز التنفسي للصغار');
INSERT INTO `MedicalFileSpecialty` (`id`,`sectionCode`,`name`) VALUES (73,'01050104 Orthopedics Consultant Examination','جراحة العظام');
