/*
-- Query: SELECT * FROM test.Specialty
LIMIT 0, 1000

-- Date: 2024-07-03 18:50
*/
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (1,'العيون','OPHTHALMOLOGY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0108 OPHTHALMOLOGY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (2,'الأطفال','PEDIATRICS','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0103 PEDIATRICS -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (3,'الأسنان','DENTISTRY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0160 Dentistry');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (4,'النساء','OBSTETRICS AND GYNECOLOGY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0104 OBSTETRICS AND GYNECOLOGY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (5,'الباطنة','INTERNAL MEDICINE','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0101 INTERNAL MEDICINE -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (6,'جراحة عامة','GENERAL SURGERY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0102 GENERAL SURGERY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (7,'العظام','ORTHOPEDICS','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0105 ORTHOPEDICS -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (8,'المسالك','UROLOGY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0106 UROLOGY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (9,'الأشعة','RADIOLOGY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'02 RADIOLOGY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (10,'الأعصاب','NEUROLOGY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0116 NEUROLOGY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (11,'الطب النفسي','PSYCHIATRY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0113 PSYCHIATRY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (12,'جراحة الأعصاب','NEUROSURGERY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0115 NEUROSURGERY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (13,'العلاج الطبيعي','PHYSIOTHERAPY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0180 PHYSIOTHERAPY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (14,'الجلدية','DERMATOLOGY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0109 DERMATOLOGY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (15,'الأنف والأذن والحنجرة','ENT','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0107 ENT -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (16,'الغدد الصماء','ENDOCRINOLOGY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0114 ENDOCRINOLOGY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (17,'القلب','CARDIOLOGY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0111 CARDIOLOGY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (18,'الطوارئ','EMERGENCY MEDICINE','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0122 EMERGENCY MEDICINE -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (19,'جراحة التجميل','PLASTIC SURGERY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0135 PLASTIC SURGERY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (20,'المعدات الطبية والأدوات','MEDICAL EQUIPMENTS AND TOOLS','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0185 MEDICAL EQUIPMENTS AND TOOLS -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (21,'الكلى','NEPHROLOGY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0121 NEPHROLOGY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (22,'الدم','HEMATOLOGY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0117 HEMATOLOGY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (23,'الجهاز التنفسي','RESPIRATORY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0119 RESPIRATORY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (24,'جراحة الفك والوجه','MAXILLOFACIAL SURGERY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0134 MAXILLOFACIAL SURGERY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (25,'جراحة الأوعية الدموية','VASCULAR SURGERY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0110 VASCULAR SURGERY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (26,'الجهاز الهضمي والكبد','GASTROENTEROLOGY AND HEPATOLOGY','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0112 GASTROENTEROLOGY AND HEPATOLOGY -1');
INSERT INTO `Specialty` (`id`,`name`,`en_name`,`archiveFlag`,`activeFlag`,`createdBy`,`createdDate`,`modifiedBy`,`modifiedDate`,`deletedBy`,`deletedDate`,`syncCode`,`sectionCode`) VALUES (27,'اخرى','Othar','N','Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Othar');
